sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
cache: pip
install:
  - pip install git+https://github.com/ryanhiebert/tox-travis
script: tox -v
after_success:
  - bash <(curl -s https://codecov.io/bash)
